name: main
on:
  push:
    branches:
    - main
    tags:
    - "*"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Archive release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mkhiinbg2
          path: mkhiinbg2
  release:
    needs: [pre-commit, build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4.3.1
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --latest
        env:
          OUTPUT: CHANGELOG.md
      - name: Print the changelog
        run: cat CHANGELOG.md
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          bodyFile: ./CHANGELOG.md
          skipIfReleaseExists: True
  packager:
    needs: [release]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Initial setup
        run: |
          git config --global core.ignorecase true
      - name: Clone repository using 'github.ref' from release
        uses: actions/checkout@master
      - name: Create Infinity Engine Mod Packages (.iemod and .zip)
        uses: ALIENQuake/CreateIEModZipPackage@master
        id: CreateIEModZipPackage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload iemod package to latest release
        uses: svenstaro/upload-release-action@v1-release
        if: github.ref != 'refs/heads/master'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.CreateIEModZipPackage.outputs.PackageBaseName }}.iemod
          asset_name: ${{ steps.CreateIEModZipPackage.outputs.PackageBaseName }}.iemod
          tag: ${{ github.ref }}
          overwrite: true
